version: '3.8'
services:
  web:
    build: ../
    restart: always
    volumes:
# removed as unnecessary after location changed
#      - static_value:/app/backend/bot_django_project/static/
#      - media_value:/app/backend/bot_django_project/media/

# mount directories with generated bots and media separately
#  and 'static_value' location changed
#      - ../data_files:/app/backend/bot_django_project/data_files
      - ../data_files/media:/app/backend/bot_django_project/data_files/media
      - ../data_files/generated_bots:/app/backend/bot_django_project/data_files/generated_bots
# mount directories with bot_logs
      - ../data_files/bot_logs:/app/backend/bot_django_project/data_files/bot_logs

      - ../data_files/static_value:/app/backend/bot_django_project/static/
    env_file:
      - ./.env
    networks:
      cuttle_net:
        ipv4_address: 172.21.0.2

  nginx:
    image: nginx:1.22.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_value:/var/html/static/
      - ../data_files/static_value:/var/html/static/
#      - media_value:/var/html/media/
      - ../data_files/media:/var/html/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

# добавляем секцию 'command', которая перезагружает nginx каждые 6 часов,
# чтобы подгрузить новые сертификаты, если они изменились
#  Сервис certbot отвечает за взаимодействие с сервером Let's Encrypt и обновлением SSL сертификата
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    networks:
      cuttle_net:
        ipv4_address: 172.21.0.3
    depends_on:
      - web


  certbot:
    container_name: certbot
    image: certbot/certbot:v1.17.0
    restart: unless-stopped
    entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      cuttle_net:
        ipv4_address: 172.21.0.4
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


# объявление volumes', доступ к которым необходим из каждого запущенного в общей сети контейнера
# в данный момент нет таких - поэтому закомменчено
#volumes:
#  static_value:
#  media_value:

networks:
  cuttle_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
